import:
  - "~/.alacritty-colorscheme/themes/solarized_light.yaml"
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: screen

window:
  opacity: 0.7
  startup_mode: Fullscreen

scrolling:
  # we use tmux instead
  history: 0

font:
  # Normal (roman) font face
  normal:
    family: 'CaskaydiaCove Nerd Font Mono'
    # The `style` can be specified to pick a specific face.
    #style: Regular
  size: 8.5

#draw_bold_text_with_bright_colors: false

colors:
  # Transparent cell backgrounds
  #
  # Whether or not `window.opacity` applies to all cell backgrounds or only to
  # the default background. When set to `true` all cells will be transparent
  # regardless of their background color.
  transparent_background_colors: false

bell:
  # Ease
  # EaseOut
  # EaseOutSine
  # EaseOutQuad
  # EaseOutCubic
  # EaseOutQuart
  # EaseOutQuint
  # EaseOutExpo
  # EaseOutCirc
  # Linear
  animation: EaseOutExpo
  # Duration of the visual bell flash in milliseconds. A `duration` of `0` will
  # disable the visual bell animation.
  duration: 0
  color: '#ffffff'
  command: None

cursor:
  style:
    # ▇ Block
    # _ Underline
    # | Beam
    shape: Block
    # Never: Prevent the cursor from ever blinking
    # Off: Disable blinking by default
    # On: Enable blinking by default
    # Always: Force the cursor to always blink
    blinking: Off
  #blink_interval: 750
  #blink_timeout: 5
  unfocused_hollow: true
  thickness: 0.15

live_config_reload: true

# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g.
# `/bin/fish`. Entries in `shell.args` are passed unmodified as arguments to the
# shell.
#
# Default:
#   - (Linux/BSD/macOS) `$SHELL` or the user's login shell, if `$SHELL` is unset
#   - (Windows) powershell
shell:
  program: tmux

key_bindings:
  - { key: Paste,                                       action: Paste          }
  - { key: Copy,                                        action: Copy           }
  - { key: L,         mods: Control,                    action: ClearLogNotice }
  - { key: L,         mods: Control, mode: ~Vi|~Search, chars: "\x0c"          }
  - { key: PageUp,    mods: Shift,   mode: ~Alt,        action: ScrollPageUp   }
  - { key: PageDown,  mods: Shift,   mode: ~Alt,        action: ScrollPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop    }
  - { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }
  - { key: V,              mods: Control|Shift, mode: ~Vi,        action: Paste            }
  - { key: C,              mods: Control|Shift,                   action: Copy             }
  - { key: F,              mods: Control|Shift, mode: ~Search,    action: SearchForward    }
  - { key: B,              mods: Control|Shift, mode: ~Search,    action: SearchBackward   }
  - { key: C,              mods: Control|Shift, mode: Vi|~Search, action: ClearSelection   }
  - { key: Insert,         mods: Shift,                           action: PasteSelection   }
  - { key: Key0,           mods: Control,                         action: ResetFontSize    }
  - { key: Equals,         mods: Control,                         action: IncreaseFontSize }
  - { key: Plus,           mods: Control,                         action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,                         action: IncreaseFontSize }
  - { key: Minus,          mods: Control,                         action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control,                         action: DecreaseFontSize }

