* Dotfiles Repo
** Windows

*** Init

#+BEGIN_SRC powershell
node ./init-windows.js
#+END_SRC

*** Tools
- ngrok - tunnel to localhost on local machine
- mdloader - configure massdrop keyboards. Usage:
#+BEGIN_SRC powershell
./mdloader --first --download FILE_NAME --restart
#+END_SRC
  - After flashing the firmware, press the reset button under keyboard for changes to take effect

** Linux

*** Init

#+BEGIN_SRC shell
node ./init-windows.js
#+END_SRC

*** Tools
- ripgrep
- TeX Live
- ImageMagick
- Wakatime (time tracking)
- emacs
  - Doom
  - Spacemacs
  - Chemacs2 (switcher)
- vim
  
** Scripts
Found in the ./bin folder and inside a specific program, these are useful scripts meant to accomplish specific functions.

*** AHK
AutoHotKey, used for creating custom shortcuts, very powerful

* Architecture

Sync dotfiles to this directory by creating symbolic links in the local user's home directory. Uses the synchronous node fs functions. Ensure node is at least version 16.

* Troubleshooting

- Sometimes have trouble with some symlinks not creating. If this is the case, manually delete dotfiles and then rerun init.

** Hosts

For my private VPN. Setup:

aws s3 cp hosts.txt s3://sk-hosts/hosts.txt

https://sk-hosts.s3.us-west-1.amazonaws.com/hosts.txt
