wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  exitMessage:
    display: false
  mods:
    gcal:
      colors:
        title: "red"
        eventTime: "lightblue"
        description: "yellow"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      calendarReadLevel: "reader"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "stephenjkrider@gmail.com"
      enabled: true
      eventCount: 15
      hourFormat: "12"
      multiCalendar: true
      position:
        top: 0
        left: 0
        height: 999
        width: 999
      refreshInterval: 5m
      secretFile: "~/.config/wtf/gcal/credentials.json"
      showDeclined: true
      showEndTime: false
      timezone: "America/Vancouver"
      withLocation: true
