alias psl='powershell -nologo'
alias xclip='xclip -selection c'
alias brain2='code ~/brain2/dendron.code-workspace'
alias fcd='cd $(fd | fzf)'
alias f='fcd'
alias glogout='gnome-session-quit'
alias nextonic='tectonic -X'
alias new='alacritty &'
